"""
Milestone 1 — the walking skeleton. No LLM, no UI.

Hand-written IR -> Flow XML -> checkOnly deploy against a real org. If this
passes validation, every remaining piece is straightforward work.

    python spike.py                      # generate + print the XML only
    python spike.py --validate --org     # checkOnly, credentials from the sf CLI
    python spike.py --validate           # checkOnly, credentials typed at the prompt

With --org the access token comes straight from `sf org display`, which is the
easy path: a session id copied out of a browser is scoped to the domain it was
copied from, so a Lightning cookie will not authenticate against the API host.
Without --org the session id is read without echoing, so it never reaches shell
history. SF_INSTANCE_URL / SF_SESSION_ID also work, for CI.
"""

from __future__ import annotations

import argparse
import asyncio
import getpass
import os
import sys
from typing import Optional

from flowforge.ir import (
    Condition,
    Decision,
    FieldValue,
    Flow,
    GetRecords,
    Outcome,
    RecordFilter,
    RecordUpdate,
    Start,
    Value,
)
from flowforge.xmlgen import generate

FLOW_API_NAME = "FlowForge_Spike_High_Value_Account"


def build_flow() -> Flow:
    """
    When an Opportunity is won, find its Account and — if the deal is large —
    mark the Account as Hot. Exercises Start filters, GetRecords, Decision with
    a structured condition, RecordUpdate, and a path that simply ends.
    """
    return Flow(
        api_name=FLOW_API_NAME,
        label="FlowForge Spike - High Value Account",
        description="Generated by flowforge. Marks Accounts hot on large won deals.",
        start=Start(
            object="Opportunity",
            record_trigger_type="CreateAndUpdate",
            trigger_type="RecordAfterSave",
            filters=[
                RecordFilter(
                    field="StageName",
                    operator="EqualTo",
                    value=Value(string_value="Closed Won"),
                )
            ],
            next="Get_Account",
        ),
        elements=[
            GetRecords(
                name="Get_Account",
                label="Get Account",
                object="Account",
                filters=[
                    RecordFilter(
                        field="Id",
                        operator="EqualTo",
                        value=Value(element_reference="$Record.AccountId"),
                    )
                ],
                first_record_only=True,
                store_output_automatically=True,
                next="Is_High_Value",
            ),
            Decision(
                name="Is_High_Value",
                label="Is High Value?",
                outcomes=[
                    Outcome(
                        name="High_Value",
                        label="High Value",
                        conditions=[
                            Condition(
                                left="$Record.Amount",
                                operator="GreaterThan",
                                right=Value(number_value=10000),
                            )
                        ],
                        next="Mark_Account_Hot",
                    )
                ],
                default_outcome_label="Standard",
                # No `next` on the default path: the flow just ends there.
                next=None,
            ),
            # Update by criteria rather than by input_reference: Salesforce
            # forbids combining inputAssignments with an sObject reference, and
            # the record from Get_Account is stored automatically, which makes
            # it read-only to an Assignment.
            RecordUpdate(
                name="Mark_Account_Hot",
                label="Mark Account Hot",
                object="Account",
                filters=[
                    RecordFilter(
                        field="Id",
                        operator="EqualTo",
                        value=Value(element_reference="Get_Account.Id"),
                    )
                ],
                fields=[FieldValue(field="Rating", value=Value(string_value="Hot"))],
                next=None,
            ),
        ],
    )


async def validate(flow_xml: str, use_cli: bool, org_alias: Optional[str]) -> int:
    from flowforge.sfdc import validate_flow

    if use_cli:
        from flowforge.orgs import SfCliError, get_org

        try:
            org = get_org(org_alias)
        except SfCliError as exc:
            print(exc, file=sys.stderr)
            return 2
        print(f"Using sf CLI org {org.alias} ({org.username})")
        instance_url, session_id = org.instance_url, org.access_token
    else:
        instance_url = os.environ.get("SF_INSTANCE_URL") or input(
            "Instance URL (e.g. https://your-domain.my.salesforce.com): "
        ).strip()
        # getpass keeps the session id off the screen and out of shell history.
        session_id = os.environ.get("SF_SESSION_ID") or getpass.getpass(
            "Session ID (input hidden): "
        ).strip()

    if not instance_url or not session_id:
        print("Both an instance URL and a session id are required.", file=sys.stderr)
        return 2

    print(f"Validating {FLOW_API_NAME} against {instance_url} (checkOnly)...")
    result = await validate_flow(
        instance_url, session_id, FLOW_API_NAME, flow_xml, check_only=True
    )

    print(f"\nStatus:  {result.status}")
    print(f"Success: {result.success}")
    if result.error_message:
        print(f"Error:   {result.error_message}")
    for failure in result.failures:
        print(f"  {failure}")
    return 0 if result.success else 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--validate", action="store_true", help="run checkOnly against the org")
    parser.add_argument("--out", help="write the XML to this path")
    parser.add_argument(
        "--org",
        nargs="?",
        const="",
        metavar="ALIAS",
        help="take credentials from the sf CLI (optionally for a named org) "
        "instead of prompting",
    )
    args = parser.parse_args()

    flow = build_flow()  # Pydantic validates references here, before any XML exists.
    flow_xml = generate(flow)

    if args.out:
        with open(args.out, "w", encoding="utf-8") as handle:
            handle.write(flow_xml)
        print(f"Wrote {args.out}")
    else:
        print(flow_xml)

    if args.validate:
        return asyncio.run(
            validate(flow_xml, use_cli=args.org is not None, org_alias=args.org or None)
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
