"""
Permission Set grant IR.

Deliberately not generated by an LLM - unlike every other artifact type in
this package, a grant here is derived mechanically from what a plan's own
`object`/`field` steps already produced (their real api_names and types are
known ground truth by the time this runs), so there is nothing for a model
to decide. See flowtool/planner.py and server.py's plan-execute/deploy path
for why this intentionally never becomes a PlanStep: it must run after every
object/field step regardless of the plan's shape, not a depends_on list an
LLM writes, and (for the "merge into an existing Permission Set" case) needs
org credentials only available at deploy time, not at plan-execute time.

This module models only the *grants themselves* (purely additive - which
fields/objects, what access). Whether those grants land in a brand-new
Permission Set or get merged into an existing one is a server-layer decision,
not something this IR represents.
"""

from __future__ import annotations

import re
from typing import List, Optional

from pydantic import BaseModel, Field

_NON_ALNUM = re.compile(r"[^A-Za-z0-9]+")


def sanitize_api_name(label: str, max_length: int = 80) -> str:
    """
    Turn a free-text "new Permission Set" label into a valid Metadata API
    developer name - letters/digits/underscores, starting with a letter, no
    consecutive or trailing underscores (Permission Set fullName is capped at
    80 characters). Without this, a label like "CS Onboarding Access" reached
    the deploy bundle verbatim, as both the .permissionset file name and its
    package.xml member, and Salesforce rejected the whole deploy over the
    invalid name - the grant silently never landed.
    """
    slug = _NON_ALNUM.sub("_", label.strip()).strip("_")
    if not slug or not slug[0].isalpha():
        slug = f"X_{slug}" if slug else "Generated_Access"
    slug = re.sub(r"_+", "_", slug)[:max_length].rstrip("_")
    return slug or "Generated_Access"

# Field types this tool can actually create today (see ir_object.py's
# FieldType) are all genuinely editable - Formula/roll-up summaries are
# "deliberately out of scope until a real need shows up" per that module's
# own docstring. This set exists so that if a calculated type is ever added
# there, build_grant_from_steps below already does the right thing (readable
# only) with zero changes needed here.
READ_ONLY_FIELD_TYPES: frozenset = frozenset()


class FieldGrant(BaseModel):
    field_api_name: str
    object_api_name: str
    editable: bool = True
    readable: bool = True


class ObjectGrant(BaseModel):
    object_api_name: str
    allow_read: bool = True
    allow_create: bool = True
    allow_edit: bool = True
    allow_delete: bool = False


class PermissionSetGrant(BaseModel):
    label: str
    description: Optional[str] = None
    field_grants: List[FieldGrant] = Field(default_factory=list)
    object_grants: List[ObjectGrant] = Field(default_factory=list)


def build_grant_from_steps(steps, label: str) -> PermissionSetGrant:
    """
    Scans a plan's already-generated StepResults for CustomField/CustomObject
    values and turns them into a PermissionSetGrant - every other step type
    (Flow, ApexClass, LightningComponent, ...) is ignored, since Permission
    Set access is a Field/Object-Level Security concept, not something those
    other metadata types have.

    Takes `steps` untyped (rather than importing planner.StepResult) to avoid
    a circular import - planner.py imports this module, not the other way
    around. Each item only needs a `.value` attribute.
    """
    from .ir_object import CustomField, CustomObject

    field_grants: List[FieldGrant] = []
    object_grants: List[ObjectGrant] = []
    for step in steps:
        value = step.value
        if isinstance(value, CustomField):
            field_grants.append(
                FieldGrant(
                    field_api_name=value.api_name,
                    object_api_name=value.object_api_name,
                    editable=value.type not in READ_ONLY_FIELD_TYPES,
                    readable=True,
                )
            )
        elif isinstance(value, CustomObject):
            object_grants.append(ObjectGrant(object_api_name=value.api_name))

    return PermissionSetGrant(label=label, field_grants=field_grants, object_grants=object_grants)
